$rootDir = Split-Path $PSScriptRoot -Parent
$uiLibDir = Join-Path $rootDir 'assets\ui_library'
$outputFile = Join-Path $rootDir 'assets\ui_library_fallback.js'

Write-Host '[BUILD UI LIBRARY] Starting build via PowerShell...'

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/**')
[void]$sb.AppendLine(' * ui_library_fallback.js')
[void]$sb.AppendLine(' * Fallback data for offline file:// protocol execution.')
[void]$sb.AppendLine(' * Auto-generated by scripts/build_ui_library.ps1.')
[void]$sb.AppendLine(' * Ensures UI components, inspector panels, and modals can be loaded without CORS errors.')
[void]$sb.AppendLine(' */')
[void]$sb.AppendLine('')

$backtickChar = [char]96
$dollarChar = [char]36
$backslashChar = [char]92

$fileMap = @(
    @{ Var = 'window.VCTRL_UI_FALLBACK_ATOMIC'; File = 'atomic_cards.html' },
    @{ Var = 'window.VCTRL_UI_FALLBACK_ICON'; File = 'icon_cards.html' },
    @{ Var = 'window.VCTRL_UI_FALLBACK_INSPECTOR'; File = 'inspector_panels.html' },
    @{ Var = 'window.VCTRL_UI_FALLBACK_MODALS'; File = 'modals.html' }
)

foreach ($entry in $fileMap) {
    $filePath = Join-Path $uiLibDir $entry.File
    if (-not (Test-Path $filePath)) {
        Write-Error "[BUILD UI LIBRARY] Error: File not found: $filePath"
        exit 1
    }

    $rawContent = [System.IO.File]::ReadAllText($filePath, [System.Text.Encoding]::UTF8)

    # Escape backslashes, backticks, and dollar braces for template literal safety
    $escaped = $rawContent.Replace("$backslashChar", "$backslashChar$backslashChar")
    $escaped = $escaped.Replace("$backtickChar", "$backslashChar$backtickChar")
    $escaped = $escaped.Replace("${dollarChar}{", "$backslashChar${dollarChar}{")

    [void]$sb.AppendLine("$($entry.Var) = " + $backtickChar)
    [void]$sb.AppendLine($escaped)
    [void]$sb.AppendLine($backtickChar + ";`n")

    Write-Host "[BUILD UI LIBRARY] Compiled $($entry.File) -> $($entry.Var)"
}

[System.IO.File]::WriteAllText($outputFile, $sb.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "[BUILD UI LIBRARY] Success! Wrote clean bundle to $outputFile"
