$rootDir = Split-Path $PSScriptRoot -Parent
$templatesDir = Join-Path $rootDir 'assets\templates'
$outputFile = Join-Path $rootDir 'assets\templates.js'

Write-Host '[BUILD TEMPLATES] Starting build via PowerShell...'

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('/**')
[void]$sb.AppendLine(' * bychoi workspace - Embedded Templates (COMPLETE BUNDLE)')
[void]$sb.AppendLine(' * Auto-generated by scripts/build_templates.ps1.')
[void]$sb.AppendLine(' * Ensures templates can be loaded offline under file:// protocol without CORS errors.')
[void]$sb.AppendLine(' */')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('window.LF_TEMPLATES = window.LF_TEMPLATES || {};')
[void]$sb.AppendLine('window.PROJECT_METADATA_STORE = window.PROJECT_METADATA_STORE || {};')
[void]$sb.AppendLine('window.PROJECT_SCREEN_STORE = window.PROJECT_SCREEN_STORE || {};')
[void]$sb.AppendLine('window.GLOBAL_COMPONENTS_STORE = window.GLOBAL_COMPONENTS_STORE || [];')
[void]$sb.AppendLine('')

$backtickChar = [char]96
$dollarChar = [char]36
$backslashChar = [char]92

$templateFiles = Get-ChildItem -Path $templatesDir -Filter '*.html' | Sort-Object Name

foreach ($f in $templateFiles) {
    $rawContent = [System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8)

    # Escape backslashes, backticks, and dollar braces for template literal
    $escaped = $rawContent.Replace("$backslashChar", "$backslashChar$backslashChar")
    $escaped = $escaped.Replace("$backtickChar", "$backslashChar$backtickChar")
    $escaped = $escaped.Replace("${dollarChar}{", "$backslashChar${dollarChar}{")

    [void]$sb.AppendLine("window.LF_TEMPLATES['$($f.Name)'] = " + $backtickChar)
    [void]$sb.AppendLine($escaped)
    [void]$sb.AppendLine($backtickChar + ";`n")

    Write-Host "[BUILD TEMPLATES] Compiled $($f.Name)"
}

# Add standard alias mappings for runtime compatibility
[void]$sb.AppendLine('// Runtime Alias Mappings')
[void]$sb.AppendLine("window.LF_TEMPLATES['project_summary'] = window.LF_TEMPLATES['template_project_summary.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['summary'] = window.LF_TEMPLATES['template_project_summary.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['cover'] = window.LF_TEMPLATES['template_cover.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['plan'] = window.LF_TEMPLATES['template_plan.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['pc_ui'] = window.LF_TEMPLATES['template_pc_ui.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['ui'] = window.LF_TEMPLATES['template_pc_ui.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['front_ui'] = window.LF_TEMPLATES['template_pc_ui.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['mobile_ui_1'] = window.LF_TEMPLATES['template_mobile_ui_1.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['mobile_ui_2'] = window.LF_TEMPLATES['template_mobile_ui_2.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['mobile_ui_3'] = window.LF_TEMPLATES['template_mobile_ui_3.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['mobile_ui'] = window.LF_TEMPLATES['template_mobile_ui_1.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['responsive_pc_mobile'] = window.LF_TEMPLATES['template_responsive_pc_mobile.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['pc_mobile'] = window.LF_TEMPLATES['template_responsive_pc_mobile.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['responsive'] = window.LF_TEMPLATES['template_responsive_pc_mobile.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['onesphere'] = window.LF_TEMPLATES['template_onesphere.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['admin_onesphere'] = window.LF_TEMPLATES['template_onesphere.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['case_study'] = window.LF_TEMPLATES['template_case_study.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['blank'] = window.LF_TEMPLATES['template_blank.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['admin_pc_scroll'] = window.LF_TEMPLATES['template_admin_pc_scroll.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['admin_scroll'] = window.LF_TEMPLATES['template_admin_pc_scroll.html'];")
[void]$sb.AppendLine("window.LF_TEMPLATES['pc_scroll'] = window.LF_TEMPLATES['template_admin_pc_scroll.html'];")

[System.IO.File]::WriteAllText($outputFile, $sb.ToString(), [System.Text.Encoding]::UTF8)
Write-Host "[BUILD TEMPLATES] Success! Wrote clean bundle to $outputFile"
